spring:
  application:
    name: ecommerce-customers
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: ecommerce-customers
            client-secret: a8f9ad32-c380-4b58-9318-73db87352d59
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/auth/realms/ecommerce-realm
management:
  endpoints:
    web:
      exposure:
        include:
        - health
        - info
        - metrics
 
