server:
  port: 8888
spring:
  application:
    name: ecomerce-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/canisasseke/ecommerce-config-repo
   
                
                
            