spring:
  application:
    name: ecommerce-orders
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/auth/realms/ecommerce-realm
management:
  endpoints:
    web:
      exposure:
        include:
        - health
        - info
        - metrics
 
