spring:
  cloud:
    gateway:
      routes:
      - id: r1
        uri: http://localhost:9001
        predicates:
        - Path=/products/*
    discovery:
      enabled: false
  application:
    name: gateway-service
server:
  port: 8888   
           
          
      
          
