spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:4200"
            allowedMethods:
            - GET
            - OPTIONS
    discovery:
      enabled: true
  application:
    name: gateway-service
server:
  port: 8888
           
          
      
          
