spring:
  application:
    name: ecommerce-gateway
  cloud:
    discovery:
      enabled: true
    gateway:
      routes:
      - id: products_path
        uri: lb://ecommerce-products
        predicates:
        - Path=/products/**
      - id: customers_path
        uri: lb://ecommerce-customers
        predicates:
        - Path=/customers/**
      - id: orders_path
        uri: lb://ecommerce-orders
        predicates:
        - Path=/orders/**
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8080/auth/realms/ecommerce-realm
            user-name-attribute: preferred_username
        registration:
          keycloak:
            client-id: ecommerce-gateway
            client-secret: e879cad3-f91f-4e0d-af93-6e39daf3b9f5
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/auth/realms/ecommerce-realm
management:
  endpoints:
    web:
      exposure:
        include:
        - health
        - info
        - metrics
server:
  port: 8000
           
          
      
          
