spring:
  application:
    name: ecommerce-gateway
  cloud:
    discovery:
      enabled: true
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
            - GET
            - OPTIONS
            - POST
            - PUT
            - DELETE
            - OPTIONS
            - PATCH
      default-filters:
      - TokenRelay
      routes:
      - id: products_path
        uri: lb://ecommerce-products
        predicates:
        - Path=/products/**
      - id: customers_path
        uri: lb://ecommerce-customers
        predicates:
        - Path=/customers/**
      - id: orders_path
        uri: lb://ecommerce-orders
        predicates:
        - Path=/orders/**
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8080/auth/realms/ecommerce-realm
            user-name-attribute: preferred_username
        registration:
          keycloak:
            client-id: ecommerce-gateway
            client-secret: 981408da-a867-4ecd-8828-9740c8f116bb
            scope:
            - openid
            - address
            - phone
management:
  endpoints:
    web:
      exposure:
        include:
        - health
        - info
        - metrics
server:
  port: 8000
           
          
      
          
