spring:
  cloud:
    discovery:
      enabled: true
  application:
    name: ecommerce-gateway
management:
  endpoints:
    web:
      exposure:
        include:
        - health
        - info
        - metrics
server:
  port: 8000
           
          
      
          
